export const SET_MY_STREAM = 'SET_MY_STREAM';

//  General -----------------------

export const SHOW_USER_PROFILE_ACTION = 'SHOW_USER_PROFILE_ACTION';
export const GET_PHIZ_USER_PROFILE = 'GET_PHIZ_USER_PROFILE';
export const GET_PHIZ_USER_PROFILE_SCCESS = 'GET_PHIZ_USER_PROFILE_SCCESS';
export const PHIZ_USER_PROFILE_CLOSE = 'PHIZ_USER_PROFILE_CLOSE';

// General Room -----------------------
// export const GET_ROOM_DETAILS = "GET_ROOM_DETAILS";

export const GET_ROOMEDITANDDELETE = 'GET_ROOMEDITANDDELETE';
export const GET_ROOMEDITANDDELETE_SUCCESS = 'GET_ROOMEDITANDDELETE_SUCCESS';
export const GET_ROOMEDITANDDELETE_FAIL = 'GET_ROOMEDITANDDELETE_FAIL';
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';
export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const LEAVE_ROOM_SUCCESS = 'LEAVE_ROOM_SUCCESS';
// Friends -------------------------
// export const GET_MY_FRIENDSLIST = 'GET_MY_FRIENDSLIST';
// export const GET_MY_FRIENDSLIST_SUCCESS = 'GET_MY_FRIENDSLIST_SUCCESS';
export const GET_MY_FRIENDSLIST_FAIL = 'GET_MY_FRIENDSLIST_FAIL';

// Users -----------------------

export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_USER_DETAILS_BY_ID = 'GET_USER_DETAILS_BY_ID';

export const GET_USERLIST = 'GET_USERLIST';
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS';
export const GET_USERLIST_FAIL = 'GET_USERLIST_FAIL';
export const GET_SPECIAL_USER = 'GET_SPECIAL_USER';
export const GET_SPECIAL_USER_SUCCESS = 'GET_SPECIAL_USER_SUCCESS';
export const GET_SPECIAL_USER_FAIL = 'GET_SPECIAL_USER_FAIL';

export const FRIENDS_LIST = 'FRIENDS_LIST';
export const GET_FRIENDSLIST_SUCCESS = 'GET_FRIENDSLIST_SUCCESS';

export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST';
export const GET_FOLLOWING_LIST_SUCCESS = 'GET_FOLLOWING_LIST';
export const GET_FOLLOWER_LIST = 'GET_FOLLOWER_LIST';
export const GET_FOLLOWER_LIST_SUCCESS = 'GET_FOLLOWER_LIST_SUCCESS';
export const GET_REQUEST_LIST = 'GET_REQUEST_LIST';
export const GET_REQUEST_LIST_SUCCESS = 'GET_REQUEST_LIST_SUCCESS';
export const GET_IVITES = 'GET_FOLLOWING_LIST';
export const GET_IVITES_SUCCESS = 'GET_FOLLOWING_LIST_SUCCESS';

// export const GET_ALL_ROOM_LIST = "GET_ALL_ROOM_LIST";
export const SET_ALL_ROOM_LIST = 'SET_ALL_ROOM_LIST';
export const GET_FILTER_ROOMS = 'GET_FILTER_ROOMS';
export const SET_FILTER_ROOMS = 'SET_FILTER_ROOMS';

//avinay//
// User Authentication ----------------------
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_PROFILE = 'SET_PROFILE';
export const RESET_USER_FLAGS = 'RESET_USER_FLAGS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

// Room ----------------------
export const GET_ALL_ROOM_LIST = 'GET_ALL_ROOM_LIST';
export const GET_ALL_ROOM_LIST_SUCCESS = 'GET_ALL_ROOM_LIST_SUCCESS';
export const GET_ALL_ROOM_LIST_FAILURE = 'GET_ALL_ROOM_LIST_FAILURE';
export const GET_PROMOTED_ROOM_LIST = 'GET_PROMOTED_ROOM_LIST';
export const GET_PROMOTED_ROOM_LIST_SUCCESS = 'GET_PROMOTED_ROOM_LIST_SUCCESS';
export const GET_PROMOTED_ROOM_LIST_FAILURE = 'GET_PROMOTED_ROOM_LIST_FAILURE';
export const GET_FEATURED_ROOM_LIST = 'GET_FEATURED_ROOM_LIST';
export const GET_FEATURED_ROOM_LIST_SUCCESS = 'GET_FEATURED_ROOM_LIST_SUCCESS';
export const GET_FEATURED_ROOM_LIST_FAILURE = 'GET_FEATURED_ROOM_LIST_FAILURE';
export const GET_MY_ROOM_LIST = 'GET_MY_ROOM_LIST';
export const GET_MY_ROOM_LIST_SUCCESS = 'GET_MY_ROOM_LIST_SUCCESS';
export const GET_MY_ROOM_LIST_FAILURE = 'GET_MY_ROOM_LIST_FAILURE';
export const CREATE_OR_UPDATE_ROOM = 'CREATE_OR_UPDATE_ROOM';
export const CREATE_OR_UPDATE_ROOM_SUCCESS = 'CREATE_OR_UPDATE_ROOM_SUCCESS';
export const CREATE_OR_UPDATE_ROOM_FAILURE = 'CREATE_OR_UPDATE_ROOM_FAILURE';
export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAILURE = 'DELETE_ROOM_FAILURE';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';
export const GET_ROOM_DETAILS = 'GET_ROOM_DETAILS';
export const GET_ROOM_DETAILS_SUCCESS = 'GET_ROOM_DETAILS_SUCCESS';
export const GET_ROOM_DETAILS_FAILURE = 'GET_ROOM_DETAILS_FAILURE';
export const GET_ROOM_USERS = 'GET_ROOM_USERS';
export const GET_ROOM_USERS_SUCCESS = 'GET_ROOM_USERS_SUCCESS';
export const GET_ROOM_USERS_FAILURE = 'GET_ROOM_USERS_FAILURE';
export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';
export const SET_PEERS = 'SET_PEERS';
export const SET_MY_PEER = 'SET_MY_PEER';
export const RESET_FLAGS = 'RESET_FLAGS';

export const GET_MY_FRIENDSLIST = 'GET_MY_FRIENDSLIST';
export const GET_MY_FRIENDSLIST_SUCCESS = 'GET_MY_FRIENDSLIST_SUCCESS';
export const GET_MY_FRIENDSLIST_FAILURE = 'GET_MY_FRIENDSLIST_FAILURE';
export const IS_SOCKET_CONNECTED = 'IS_SOCKET_CONNECTED';
export const IS_SOCKET_JOINED = 'IS_SOCKET_JOINED';
export const SAVE_ONLINE_USERS = 'SAVE_ONLINE_USERS';
export const GET_CHATROOMS_LIST = 'GET_CHATROOMS_LIST';
export const GET_CHATROOMS_LIST_SUCCESS = 'GET_CHATROOMS_LIST_SUCCESS';
export const GET_CHATROOMS_LIST_FAILURE = 'GET_CHATROOMS_LIST_FAILURE';
